finalProject/finalProject/urls.py
from django.urls import path
from django.urls import include

urlpatterns = [
    path('',include('flea.urls')),
]

finalProject/flea/urls.py
from django.urls import path,re_path
from flea import views
from django.views.static import serve
from finalProject.settings import MEDIA_ROOT

app_name = 'flea'

urlpatterns = [
    path('',views.homepage),
    path('homepage/',views.homepage,name='homepage'),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('product/',views.product,name='product'),
    path('search/',views.search,name='search'),
    path('checkId/',views.checkId,name='checkId'),
    path('admin/',views.adminPage,name='admin'),
    path('signout/',views.signout,name='signout'),
    path('delete/',views.delete,name="delete"),
    path('modify/',views.modify,name="modify"),
    path('seller/',views.sellerPage,name='seller'),
    path('buyer/',views.buyerPage,name='buyer'),
    path('connect/',views.connectPage,name='connect'),
    path('addProduct/',views.addProduct,name='addProduct'),
    path('deal/',views.deal,name='deal'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

finalProject/flea/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):

    id = models.AutoField(primary_key=True,verbose_name='id')
    username = models.CharField(max_length=30,verbose_name='username')
    password = models.CharField(max_length=30,verbose_name='password')
    email = models.CharField(max_length=30,verbose_name='email')
    usertype = models.CharField(max_length=10,verbose_name='usertype')

    def __str__(self):
        return '%s %s'%(self.username,self.usertype)

    class Meta:
        verbose_name = 'user information'
        verbose_name_plural = 'users'


class Product(models.Model):

    id = models.AutoField(primary_key=True,verbose_name='id')
    productName = models.CharField(max_length=20,verbose_name='productName')
    picture = models.FileField(upload_to='productImage/',verbose_name='pictureName',null=True)
    seller = models.IntegerField(verbose_name='seller')
    buyer = models.IntegerField(verbose_name='buyer',default=-1)
    price = models.IntegerField(verbose_name='price')
    sellType = models.CharField(max_length=10,verbose_name='sellType')
    sellerNumber = models.CharField(max_length=20,verbose_name='sellerNumber')
    sellerName = models.CharField(max_length=20,verbose_name='sellerName')
    tradePlace = models.CharField(max_length=50,verbose_name='tradePlace')
    uploadTime = models.DateTimeField(auto_now=False, auto_now_add=True)
    endTime = models.DateTimeField(auto_now=False, auto_now_add=False,null=True)

    def __str__(self):
        return self.productName

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class AuctionInformation(models.Model):

    id = models.AutoField(primary_key=True,verbose_name='id')
    product = models.IntegerField(verbose_name='product')
    bidder = models.IntegerField(verbose_name='bidder')
    price = models.IntegerField(verbose_name='price')
    uploadTime = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return '%s %s'%(self.product,self.price)

    class Meta:
        verbose_name = 'AuctionInformation'
        verbose_name_plural = 'AuctionInformations'


class FeedBackInformation(models.Model):

    id = models.AutoField(primary_key=True,verbose_name='id')
    name = models.CharField(max_length=20,verbose_name='name')
    email = models.CharField(max_length=30,verbose_name='email')
    usertype = models.CharField(max_length=10,verbose_name='usertype')
    inner = models.CharField(max_length=200,verbose_name='inner')

    def __str__(self):
        return self.inner

    class Meta:
        verbose_name = 'FeedBackInformation'
        verbose_name_plural = 'FeedBackInformations'


class Cart(models.Model):

    id = models.AutoField(primary_key=True,verbose_name='id')
    buyer = models.IntegerField(verbose_name='buyer')
    product = models.IntegerField(verbose_name='product')
    uploadTime = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return '%s %s'%(self.product,self.buyer)

    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'

finalProject/flea/views.py
from django.shortcuts import render
from django.http import HttpResponse
from flea import models
import datetime,pytz
utc=pytz.UTC

# Create your views here.
def homepage(request):
    #if 'id' in request.session.keys():
    return render(request,'flea/homepage.html',locals())

def login(request):
    if request.method == "POST":
        username = request.POST.get("id")
        usertype = request.POST.get("type")
        password = request.POST.get("password")
        res = models.UserInfo.objects.filter(username=username,usertype=usertype,password=password).values()
        if len(res) == 1:
            request.session['id'] = res[0]["id"]
            request.session['username'] = res[0]["username"]
            if res[0]['usertype'] == "0":
                request.session['usertype'] = "admin"
            elif res[0]['usertype'] == "1":
                request.session['usertype'] = "seller"
            elif res[0]['usertype'] == "2":
                request.session['usertype'] = "buyer"
            return HttpResponse("1")
        else:
            return HttpResponse("0")
    elif request.method == "GET":
        return render(request,'flea/login.html',locals())

def signup(request):
    if request.method == "POST":
        username = request.POST.get("id")
        usertype = request.POST.get("type")
        email = request.POST.get("email")
        password = request.POST.get("password")
        try:
            models.UserInfo.objects.create(username=username,usertype=usertype,email=email,password=password)
            return HttpResponse("1")
        except:
            return HttpResponse("0")
    elif request.method == "GET":
        return render(request,'flea/signup.html',locals())

def product(request):
    if "id" in request.GET:
        productId = request.GET.get("id")
        product = models.Product.objects.filter(id=productId).values()[0]
        try:
            endtime = product["endTime"].__format__('%Y/%m/%d %H:%M:%S')
        except:
            pass
        return render(request,'flea/product.html',locals())
    else:
        return render(request,'flea/homepage.html',locals())

def search(request):
    if request.method == "POST":
        searchType = request.POST.get("type")
        if searchType == "name":
            res = models.Product.objects.filter(productName__contains=request.POST.get("key1")).values()
            result = list()
            for r in res:
                l = list()
                for k in r.keys():
                    if k == "uploadTime":
                        l.append(r["uploadTime"].__format__('%Y/%m/%d %H:%M:%S'))
                        continue
                    elif k == "endTime":
                        if r["endTime"] == None:
                            l.append("null")
                        else:
                            l.append(r["endTime"].__format__('%Y/%m/%d %H:%M:%S'))
                    else:
                        l.append(r[k])
                if r["sellType"] == "0":
                    if r["buyer"] == -1:
                        l.append("Selling")
                    else:
                        l.append("Sold")
                else:
                    if utc.localize(r["endTime"]) > utc.localize(datetime.datetime.now()):
                        l.append("Bidding")
                    else:
                        l.append("End Bidded")
                result.append(l)
            return HttpResponse(str(result))
        else:
            res = models.Product.objects.filter(price__range=[request.POST.get("key1"),request.POST.get("key2")]).values()
            result = list()
            for r in res:
                l = list()
                for k in r.keys():
                    if k == "uploadTime":
                        l.append(r["uploadTime"].__format__('%Y/%m/%d %H:%M:%S'))
                        continue
                    elif k == "endTime":
                        if r["endTime"] == None:
                            l.append("null")
                        else:
                            l.append(r["endTime"].__format__('%Y/%m/%d %H:%M:%S'))
                    else:
                        l.append(r[k])
                if r["sellType"] == "0":
                    if r["buyer"] == -1:
                        l.append("Selling")
                    else:
                        l.append("Sold")
                else:
                    if utc.localize(r["endTime"]) < utc.localize(datetime.datetime.now()):
                        l.append("Bidding")
                    else:
                        l.append("End Bidded")
                result.append(l)
            return HttpResponse(str(result))

def checkId(request):
    if request.method == "POST":
        id = request.POST.get("id")
        userType = request.POST.get("type")
        res = models.UserInfo.objects.filter(username=id,usertype=userType)
        if len(res) == 0:
            return HttpResponse("1")
        else:
            return HttpResponse("0")
    else:
        return HttpResponse("0")

def adminPage(request):
    if request.method == "GET":
        userInfo = models.UserInfo.objects.all()
        products = models.Product.objects.all()
        feedback = models.FeedBackInformation.objects.all()
        return render(request,'flea/admin.html',locals())

def signout(request):
    request.session.flush()
    return HttpResponse("1")

def delete(request):
    if request.POST.get("type") == "0":
        id = int(request.POST.get("id"))
        try:
            models.Cart.objects.filter(buyer=id).delete()
        except:
            pass
        try:
            res = models.Product.objects.filter(seller=id).value()
            for p in res:
                try:
                    models.AuctionInformation.objects.filter(product=p["id"]).delete()
                except:
                    continue
            models.Product.objects.filter(seller=id).delete()

        except:
            pass
        try:
            models.Product.objects.filter(buyer=id).delete()
        except:
            pass
        try:
            models.UserInfo.objects.filter(id=id).delete()
            return HttpResponse("1")
        except:
            return HttpResponse("0")
    elif request.POST.get("type") == "1":
        id = request.POST.get("id")
        try:
            models.Product.objects.filter(id=int(id)).delete()
            modeles.AuctionInformation.objects.filter(product=int(id)).delete()
            return HttpResponse("1")
        except:
            return HttpResponse("1")
    else:
        return HttpResponse("0")

def modify(request):
    if request.POST.get("type") == "0":
        data = eval(request.POST.get("data"))
        try:
            for rolumn in data:
                models.UserInfo.objects.filter(id=rolumn[0]).update(username=rolumn[1],password=rolumn[2],email=rolumn[3],usertype=rolumn[4])
            return HttpResponse("1")
        except:
            return HttpResponse("0")
    elif request.POST.get("type") == "1":
        data = eval(request.POST.get("data"))
        try:
            for rolumn in data:
                models.Product.objects.filter(id=int(rolumn[0])).update(productName=rolumn[1],tradePlace=rolumn[2])
            return HttpResponse("1")
        except:
            return HttpResponse("0")

def sellerPage(request):
    products = models.Product.objects.filter(seller=int(request.session["id"])).values()
    auction = models.AuctionInformation.objects.all().values()
    users = models.UserInfo.objects.all().values()
    return render(request,'flea/seller.html',locals())

def buyerPage(request):
    orders = models.Product.objects.filter().values()
    auctions = models.AuctionInformation.objects.filter(bidder=int(request.session["id"])).values()
    cart = models.Cart.objects.filter(buyer=int(request.session["id"])).values()
    return render(request,'flea/buyer.html',locals())

def connectPage(request):
    return render(request,'flea/connect.html',locals())

def addProduct(request):
    id = request.session["id"]
    img = request.FILES.get("img")
    productName = request.POST.get("productname")
    price = request.POST.get("price")
    sellerName = request.POST.get("sellerName")
    sellerPhone = request.POST.get("sellerPhone")
    address = request.POST.get("address")
    selltype = request.POST.get("type")
    if selltype == "1":
        try:
            endtime = datetime.datetime.now() + datetime.timedelta(hours=int(request.POST.get("endtime")))
            models.Product.objects.create(productName=productName,picture=img,seller=id,price=price,sellType=selltype,sellerNumber=sellerPhone,sellerName=sellerName,tradePlace=address,endTime=endtime)
            return HttpResponse("1")
        except:
            return HttpResponse("0")
    else:
        try:
            models.Product.objects.create(productName=productName,picture=img,seller=id,price=price,sellType=selltype,sellerNumber=sellerPhone,sellerName=sellerName,tradePlace=address)
            return HttpResponse("1")
        except:
            return HttpResponse("0")

def deal(request):
    if request.POST.get("type") == "0":#add to cart
        try:
            productid = int(request.POST.get("id"))
            models.Cart.objects.get_or_create(buyer=request.session['id'],product=productid)
            return HttpResponse("1")
        except:
            return HttpResponse("0")
        return HttpResponse("2")

    elif request.POST.get("type") == "1":#buy
        try:
            productid = int(request.POST.get("id"))
            models.Product.objects.filter(id=productid).update(buyer=request.session['id'])
            return HttpResponse("1")
        except:
            return HttpResponse("0")
        return HttpResponse("2")
    elif request.POST.get("type") == "2":
        try:
             productid = int(request.POST.get("id"))
             price = int(request.POST.get("price"))

finalProject/flea/templates/flea/buyer.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<!-- css part -->
<link rel="stylesheet" href="{% static 'css/buyer.css' %}">
{% if request.session.usertype == NULL %}
<meta http-equiv='refresh' content='1;url={% url 'flea:homepage' %}'>
{% elif request.session.usertype != "buyer" %}
<meta http-equiv='refresh' content="1;url='/{{request.session.usertype}}/'">
{% endif %}
{% if request.session.usertype == NULL or request.session.usertype != "buyer" %}
<style>body{display:none;}</style>
{% endif %}
{% endblock %}

{% block inner %}<!-- inner part -->
<div id="menu">
    <a>_for buyer</a>
    <a href="{% url 'flea:buyer' %}?page=home">Home</a>
    <a href="{% url 'flea:buyer' %}?page=list">Product List</a>
    <a href="{% url 'flea:connect' %}">Connect Us</a>
    <a href="{% url 'flea:buyer' %}?page=cart"><button style="background: url('{% static 'image/cart.png' %}') center center; width:40px;height: 40px;background-size: 100% 100%;border:none;border-radius:0;"></button></a>
</div>
{% if request.GET.page == "home" or request.GET.page == NULL %}
<div id="ad">
    <img src="{% static 'image/logo.png' %}">
    <div id='logoInner'>
        <span>Fun Shopping</span><br>
        <span>SKKU FLEA MARKET</span><br><br>
        <span>Anabada is a Korean word which has four meanings - "Saving, Sharing, Exchanging, and Reusing". The campaign has helped South Korea overcome financially hard times.</span>
        <button onclick="showSearchingPage()" id='showSearchingPage'>Find Your Product!</button>
    </div>
</div>
<div id='searchbox' style='display:none'>
	<span>Search By </span>
	<select id='searchtype' onchange='changeSearchType()'>
		<option value='1' selected='selected'>Name</option>
		<option value='2'>Price</option>
	</select>
	<div id='searchingByName'>
		<table><tr><td style='text-align:right'><label for='searchingName'>Name:</label></td><td><input type='text' id='searchingName'></td><td><button onclick="search('name')" class='search'></button></td></tr></table>
	</div>
	<div id='searchingByPrice'>
		<table><tr><td><label for='lowprice'>Price:</label></td><td><input type='number' id='lowprice'></td><td> - </td><td><input type='number' id='hightprice'></td><td><button onclick="search('price')" class='search'></button></td></tr></table>
	</div>
</div>

<div id='searchingReasult'></div>
{% elif request.GET.page == "list" %}
{% now "Y-m-d-s" as time %}
<div class='buyerTables'>
    <h1>All Orders</h1>
    <table rules='none' class='buyerTableItem'>
        <tr><th>Product Name</th><th>Current Price</th><th>Trading Place</th><th>Phone Number</th><th>Status</th><th>Seller Name</th></tr>
        {% for pro in orders %}
            {% if pro.sellType == "0" and pro.buyer == request.session.id %}
                <tr><td><a href="{% url 'flea:product' %}?id={{pro.id}}">{{pro.productName}}</a></td><td>{{pro.price}}</td><td>{{pro.tradePlace}}</td><td>{{pro.sellerNumber}}</td><td>Order Completed</td><td>{{pro.sellerName}}</td></tr>
            {% elif pro.sellType == "1" %}
                {% if pro.endTime|date:"Y-m-d-s" < time %}
                    {% for a in auctions %}
                        {% if a.bidder == request.session.id %}
                            <tr><td><a href="{% url 'flea:product' %}?id={{pro.id}}">{{pro.productName}}</a></td><td>{{a.price}}</td><td>{{pro.tradePlace}}</td><td>{{pro.sellerNumber}}</td><td>
                                {% if a.price == pro.price %}
                                Bidding(You are the highest)
                                {% else %}
                                Bidding(You are not he highest)
                                {% endif %}
                            </td><td>{{pro.sellerName}}</td></tr>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    {% for a in auctions %}
                        {% if a.bidder == request.session.id %}
                            <tr><td><a href="{% url 'flea:product' %}?id={{pro.id}}">{{pro.productName}}</a></td><td>{{a.price}}</td><td>{{pro.tradePlace}}</td><td>{{pro.sellerNumber}}</td><td>
                                {% if a.price == pro.price %}
                                Bidding Succeed!
                                {% else %}
                                Bidding Failed!
                                {% endif %}
                            </td><td>{{pro.sellerName}}</td></tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endif %}
        {% endfor %}
    </table>
</div>
{% elif request.GET.page == "cart" %}
{% now "Y-m-d-s" as time %}
<div class='buyerTables'>
    <h1>Cart</h1>
    <table rules='none' class='buyerTableItem'>
        <tr><th>Product Name</th><th>Current Price</th><th>Trading Place</th><th>Phone Number</th><th>Status</th><th>Seller Name</th></tr>
        {% for c in cart %}
                {% for p in orders %}
                    {% if p.id == c.product %}
                    <tr>
                        <td>
                            <a href="{% url 'flea:product' %}?id={{c.product}}">{{p.productName}}</a>
                        </td>
                        <td>{{p.price}}</td>
                        <td>{{p.tradePlace}}</td>
                        <td>{{p.sellerNumber}}</td>
                        <td>
                            {% if p.sellType == "0" %}
                                {% if p.buyer != -1 %}
                                    Sold
                                {% else %}
                                    Selling
                                {% endif %}
                            {% else %}
                                {% if p.endTime|date:"Y-m-d-s" > time %}
                                Bidding
                                {% else %}
                                End Bidding
                                {% endif %}
                            {% endif %}
                        </td>
                        <td>{{p.sellerName}}</td>
                    </tr>
                    {% endif %}
                {% endfor  %}
        {% endfor %}
    </table>
</div>
{% endif %}

{% endblock %}

{% block script %}<!-- script part -->
{% endblock %}

finalProject/flea/templates/flea/connect.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<!-- css part -->
<link rel="stylesheet" href="{% static 'css/connect.css' %}">
{% endblock %}

{% block inner %}<!-- inner part -->
<div id='contentpage'>
    <div id='one'>
        <span class='title'>SungKyunKwan University</span><br>
        <span class='inner'>2066,Scobu-ro,Jangun-gu,Suwon-st,Gyeonggl-do</span><br><br>
        <span class='title'>010-1234-5678</span><br>
        <span class='inner'>Mon to Fri 9am to 6am</span><br><br>
        <span class='title'>jooohyednjs@gmail.com</span><br>
        <span class='inner'>Send us your request anytime!</span>
    </div>
    <div id='two'>
        <input type='text' placeholder='Enter Your Name' id='contentname'><br>
        <input type='text' placeholder='Enter Email Address' id='contentemail'><br>
        <input type='text' placeholder='Enter Your Type(buyer/seller)' id='type'>
    </div>
    <div id='three'>
        <textarea id='inner' cols='40'rows='13' placeholder='Enter Message'></textarea>
    </div>
</div>
<button id='abtn' class='btn' onclick='connect()'>Send</button>
{% endblock %}

{% block script %}<!-- script part -->

{% endblock %}

finalProject/flea/templates/flea/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<!-- css part -->
<link rel="stylesheet" href="{% static 'css/homepage.css' %}">
{% endblock %}

{% block inner %}<!-- inner part -->
<div id="menubox">
	
	<div class="box left">
		<span>
			Already have an account?
		</span><br><br>
		<span>
			Login now and enjoy SKKU Flea Market!
		</span><br><br>
		<a href="{% url 'flea:login' %}"><button>Login Now</button></a>
	</div>
	
	<div class="box right">
		<span>
			New to our website?
		</span><br><br>
		<span>
			This web page is SKKU Flea Market!
		</span><br><br>
		<a href="{% url 'flea:signup' %}"><button>Create an Account</button></a>
	</div>
	
</div>

<div id='searchbox'>
	<span>Search By </span>
	<select id='searchtype' onchange='changeSearchType()'>
		<option value='1' selected='selected'>Name</option>
		<option value='2'>Price</option>
	</select>
	<div id='searchingByName'>
		<table><tr><td style='text-align:right'><label for='searchingName'>Name:</label></td><td><input type='text' id='searchingName'></td><td><button onclick="search('name')" class='search'></button></td></tr></table>
	</div>
	<div id='searchingByPrice'>
		<table><tr><td><label for='lowprice'>Price:</label></td><td><input type='number' id='lowprice'></td><td> - </td><td><input type='number' id='hightprice'></td><td><button onclick="search('price')" class='search'></button></td></tr></table>
	</div>
</div>

<div id='searchingReasult'></div>

{% endblock %}

{% block script %}<!-- script part -->
{% endblock %}

finalProject/flea/templates/flea/seller.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<!-- css part -->
<link rel="stylesheet" href="{% static 'css/seller.css' %}">
{% if request.session.usertype == NULL %}
<meta http-equiv='refresh' content='1;url={% url 'flea:homepage' %}'>
{% elif request.session.usertype != "seller" %}
<meta http-equiv='refresh' content="1;url='/{{request.session.usertype}}/'">
{% endif %}
{% if request.session.usertype == NULL or request.session.usertype != "seller" %}
<style>body{display:none;}</style>
{% endif %}
{% endblock %}

{% block inner %}<!-- inner part -->
<div id="menu">
    <a>_for seller</a>
    <a href="{% url 'flea:seller' %}?page=home">Home</a>
    <a href="{% url 'flea:seller' %}?page=list">Product List</a>
    <a href="{% url 'flea:connect' %}">Connect Us</a>
</div>
{% if request.GET.page == "home" or request.GET.page == NULL %}
<div id="ad">
    <img src="{% static 'image/logo.png' %}">
    <div id='logoInner'>
        <span>Fun Shopping</span><br>
        <span>SKKU FLEA MARKET</span><br><br>
        <span>Anabada is a Korean word which has four meanings - "Saving, Sharing, Exchanging, and Reusing". The campaign has helped South Korea overcome financially hard times.</span>
        <button onclick="showUploadTable()" id='showUploadTable'>Upload Product!</button>
    </div>
</div>
<div id='addProductTable' style="display: none;">
    <div id="imagebox" onclick="selectImage()">
        <span>Click here to browse</span><br><span>your product image file</span>
    </div>
    <div id='pic' onclick='selectImage()' style='display:none'><img src='' id='imageShow'></div>
    <table id='inputTable'>
        <tr><td><input type='text' placeholder='Enter Product Name' id='productName' class='input'></td></tr>
        <tr><td><input type='text' placeholder='Enter Product Price' id='productPrice' class='input'></td></tr>
        <tr><td><input type='text' placeholder='Enter Your Name' id='sellerName' class='input'></td></tr>
        <tr><td><input type='telephone' placeholder='Enter Your Phone Number' id='sellerPhone' class='input'></td></tr>
        <tr><td><input type='text' placeholder='Enter Trading Place' id='address' class='input'></td></tr>
        <tr><td><input type='checkbox' id='flea' onclick="selectSellType('flea')"><label for='flea'>Flea Market</label></td></tr>
        <tr><td><input type='checkbox' id='auction' onclick="selectSellType('auction')"><label for='auction'>Auction</label></td></tr>
        <tr id='endtimebox'>
            <td>
                <label for='endtime'>End Time: </label>
                <input type="number" id='endtime' class="input">
                Hour(s)
            </td>
        </tr>
        <tr><td style='float:right;'><button onclick='addProduct()' class='submitButtons'>Sell Now</button></td></tr>
    </table>
</div>
<input type='file' accept='image/*' style='display:none' id='hideInput' onchange='showImage(this)'>
{% elif request.GET.page == "list" %}
<div id="allProducts">
    <button onclick="showUploadTable()">Add Product</button>
    <table rules="none">
        <tr><th>Product Name</th><th>Current Price</th><th>Trade Place</th><th>Status</th><th>History</th><th>Delete</th></tr>
        {% now "Y-m-d-s" as time %}
        {% for pro in products %}
        <tr id="id{{pro.id}}" name="product" data-id="{{pro.id}}"><td onclick="accountChange('productName{{pro.id}}')" id='productName{{pro.id}}'>{{pro.productName}}</td>
            <td>{{pro.price}}</td>
            <td onclick="accountChange('tradePlace{{pro.id}}')" id='tradePlace{{pro.id}}'>{{pro.tradePlace}}</td>
            <td >
                {% if pro.sellType == "0" %}
                    {% if pro.buyer == -1 %}
                        Selling
                    {% else %}
                        Sold
                    {% endif %}
                {% elif pro.sellType == "1" %}
                    {% if pro.endTime|date:"Y-m-d-s" > time %}
                        Bidding
                    {% else %}
                        End Bidded
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% for a in auction %}
                    {% if a.product == pro.id %}
                        <span>
                            {% for u in users %}
                                {% if u.id == a.bidder %}
                                    {{u.username}}:
                                {% endif %}
                            {% endfor %}
                            {{a.uploadTime}}({{a.price}})</span><br>
                    {% endif %}
                {% endfor %}
            </td>
            <td><button onclick="deleteProduct('{{pro.id}}')" style="color: #000000;background: white;border: none;">Delete</button></td>
        </tr>
        {% empty %}
        <tr><td colspan="6" style="text-align: center;">No Data</td></tr>
        {% endfor %}
    </table>
    <button onclick="saveProducts()" id="save">SAVE</button>
</div>
<div id='addProductTable' style="display: none;">
    <div id="imagebox" onclick="selectImage()">
        <span>Click here to browse</span><br><span>your product image file</span>
    </div>
    <div id='pic' onclick='selectImage()' style='display:none'><img src='' id='imageShow'></div>
    <table id='inputTable'>
        <tr><td><input type='text' placeholder='Enter Product Name' id='productName' class='input'></td></tr>
        <tr><td><input type='text' placeholder='Enter Product Price' id='productPrice' class='input'></td></tr>
        <tr><td><input type='text' placeholder='Enter Your Name' id='sellerName' class='input'></td></tr>
        <tr><td><input type='telephone' placeholder='Enter Your Phone Number' id='sellerPhone' class='input'></td></tr>
        <tr><td><input type='text' placeholder='Enter Trading Place' id='address' class='input'></td></tr>
        <tr><td><input type='checkbox' id='flea' onclick="selectSellType('flea')"><label for='flea'>Flea Market</label></td></tr>
        <tr><td><input type='checkbox' id='auction' onclick="selectSellType('auction')"><label for='auction'>Auction</label></td></tr>
        <tr id='endtimebox'>
            <td>
                <label for='endtime'>End Time: </label>
                <input type="number" id='endtime' class="input">
                Hour(s)
            </td>
        </tr>
        <tr><td style='float:right;'><button onclick='addProduct()' class='submitButtons'>Sell Now</button></td></tr>
    </table>
</div>
<input type='file' accept='image/*' style='display:none' id='hideInput' onchange='showImage(this)'>
{% endif %}

{% endblock %}

{% block script %}<!-- script part -->
{% endblock %}

finalProject/flea/templates/flea/signup.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<!-- css part -->
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block inner %}<!-- inner part -->
<div id="menubox">
    <div class="box left">
        <span>
            Already have an account?
        </span><br><br>
        <span>
            Login now and enjoy SKKU Flea Market!
        </span><br><br>
        <a href="{% url 'flea:login' %}"><button>Login Now</button></a>
    </div>
    <div class="box right">
        <span style='font-family:papyrus'>
            Create&nbsp;&nbsp;An&nbsp;&nbsp;Account
        </span><br><br>
        <input type="checkbox" id="typeS" onclick="typecheck('s')"/><label for="typeS" id="s">Seller</label>
        <input type="checkbox" id="typeB" onclick="typecheck('b')"/><label for="typeB" id="b">Buyer</label>
        <br><br><br>
        <input type="text" id="id" placeholder="ID"><span id="state"></span>
        <br>
        <button onclick="duplicate()" id="checkid">Duplicate</button>
        <br><br>
        <input type="email" id="email" placeholder="Email Address"><br>
        <input type="password" id="password" placeholder="Password"><br>
        <input type="password" id="spassword" placeholder="Confirm Password">
        <button onclick="signup()" id="submit">REGISTER</button>
    </div>
</div>
{% endblock %}

{% block script %}<!-- script part -->
{% endblock %}